version: '3'
services:
  
  app:
    container_name: app
    build: ./docker/php
    volumes:
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
      - ./app:/var/www/html
    ports:
      - "5173:5173"
    depends_on:
      - mysql

  nginx:
    container_name: nginx
    build: ./docker/nginx
    ports:
      - "8000:80"
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./app:/usr/share/nginx/html

  mysql:
    container_name: mysql
    build: ./docker/mysql
    ports:
      - 3306:3306
    volumes:
      - mysql-volume:/var/lib/mysql
    environment:
      MYSQL_ROOT_USER: ${ROOTUSER}
      MYSQL_ROOT_PASSWORD: ${ROOTPASS}
      MYSQL_DATABASE: ${DATABASE}
      MYSQL_USER: ${USERNAME}
      MYSQL_PASSWORD: ${USERPASS}
      TZ: "Asia/Tokyo"
    env_file:
      - .env

  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin
    ports:
      - 8001:80
  
  minio:
    container_name: minio
    image: "minio/minio:RELEASE.2023-01-02T09-40-09Z.fips"
    ports:
      - 9090:9090
      - 9001:9001
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    entrypoint: sh
    command: -c "/opt/bin/minio server /export --address :9000 --console-address :9001"
    volumes:
      - ./docker/minio/data:/export
  
  createbuckets:
    image: "minio/mc"
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      echo start_up;
      sleep 5;
      /usr/bin/mc config host add myminio http://minio:9000 ${MINIO_ROOT_USER} ${MINIO_ROOT_PASSWORD};
      /usr/bin/mc mb myminio/${MINIO_BUCKET_NAME};
      exit 0;
      "

volumes:
  mysql-volume: